version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: conlang_studio_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: conlang_studio
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h localhost" ]
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  pgdata:
    name: conlang_studio_pgdata
