repo_path: /home/mmartin/projects/conlang_studio
persist_dir: /home/mmartin/projects/conlang_studio/.rag_store
chunking:
  max_tokens: 512
  overlap_tokens: 50
embedding:
  provider: fastembed
  model: BAAI/bge-small-en-v1.5
  dimension: 384
  batch_size: 256
  normalize: true
retriever:
  top_k: 6
  rerank_top_n: 10
  summary_max_tokens: 256
  min_score: 0.0
