name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * *' # daily at 03:00 UTC
  workflow_dispatch: {}
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: conlang_studio
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U app -d conlang_studio"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Typecheck
        run: pnpm typecheck
      - name: Build
        run: pnpm build
      - name: Tests
        run: pnpm test
      - name: Migration Dry Run
        run: pnpm exec tsx scripts/migrations-dry-run.ts
      - name: Exit Validation
        run: pnpm exec tsx scripts/exit-validation.ts
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: packages/testkits/test-results/
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
  nightly-property-tests:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run nightly tests
        env:
          CI: true
          NIGHTLY: 'true'
        run: pnpm -w test
  phase4-bench:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.17.1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run Phase 4 benchmark harness
        run: pnpm exec tsx scripts/benchmarks/phase4/run-benchmark.ts
      - name: Upload Phase 4 baseline
        uses: actions/upload-artifact@v4
        with:
          name: phase4-baseline
          path: benchmarks/phase4/baseline.json
